import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import { HomeOutlined, SearchOutlined, UserOutlined } from '@ant-design/icons';

import WatchlistContextProvider from '@/contexts/WatchlistContext';
import QueryClientProvider from '@/providers/QueryClientProvider';

import './globals.css';
import styles from './layout.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Disney+ Hotstar | Stream your favorite movies and more',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <WatchlistContextProvider>
            <nav className={styles.sidenav}>
              <ul>
                <li className={styles.menu}>
                  <Link href="/explore">
                    <SearchOutlined className={styles.menuIcon} />
                    <span className={styles.menuText}>Search</span>
                  </Link>
                </li>
                <li className={styles.menu}>
                  <Link href="/">
                    <HomeOutlined className={styles.menuIcon} />
                    <span className={styles.menuText}>Home</span>
                  </Link>
                </li>
                <li className={styles.menu}>
                  <Link href="/watchlist">
                    <UserOutlined className={styles.menuIcon} />
                    <span className={styles.menuText}>Watchlist</span>
                  </Link>
                </li>
              </ul>
            </nav>
            <main className={styles.content}>{children}</main>
          </WatchlistContextProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
